on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: deploying zaden_backend
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{secrets.private_key}}
        script_stop: true
        script: |
          cd /var/www/zaden_backend
          git pull
          source venv/bin/activate
          pip install -r requirements.txt
          python3 manage.py migrate
          systemctl restart gunicorn